### PR TITLE
Add guest_info column to the Vms table.

### PR DESCRIPTION
**Pull request by roliveri**
https://issues.redhat.com/browse/RHCLOUD-10836

### CODE REVIEW

**Review by slemrmartin — APPROVED** [review]
:+1:

**Review by lindgrenj6 — COMMENTED** [review]
Is there a JIRA ticket we can tie to this? That way we can keep track of all the commits for this, since I assume the next step is going to be adding it to topo-api etc.

**Comment by roliveri** [comment]
> Is there a JIRA ticket we can tie to this? That way we can keep track of all the commits for this, since I assume the next step is going to be adding it to topo-api etc.

Yes. Just added the JIRA link to the description.
Also, given this is a GEM, a new version will have to be released before it's available to the dependent code. I'm not sure of the procedure for doing that in this environment.

**Comment by lindgrenj6** [comment]
@roliveri no problem, I'll release it after merging this.

**Review by lindgrenj6 — APPROVED** [review]

**Comment by roliveri** [comment]
> @roliveri no problem, I'll release it after merging this.

@lindgrenj6  Thanks. Once done, let me know the new GEM version and I'll update the dependent PRs.

**Pull request merged**
